---
:api_key: 1a9cad5d3956798c9570c7147fef41bd
:password: dd3027fe16bb74d5e4348e40d3bbdb0a
:store: olive-piper.myshopify.com
:theme_id: 63084357
:ignore_files:
- config/settings.html
- config.yml
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
